### ISSUE TITLE
Build fails as its unable to create the .repoconfig in the root

### ISSUE THREAD

**Issue by dhanainme** [kylemanna/docker-aosp#9]
I ve been trying to follow the instructions of running build-kitkat.sh.
How ever the build fails as its unable to create the .repoconfig in the root. I presume the .repoconfig must be created in the home dir of the user and not in /
I also could not find run.sh in the docker container in /usr/local/bin/run.sh

Env : Ubuntu 14.04
I have a user group called docker and I m running the script from a user in that usergroup.

Log : 

```
user@palm:~/docker-aosp/tests$ ./build-kitkat.sh
+ '[' '' = docker ']'
+ aosp_url=https://raw.githubusercontent.com/kylemanna/docker-aosp/master/utils/aosp
+ args='bash run.sh docker'
+++ dirname ./build-kitkat.sh
++ cd .
++ pwd -P
++ basename ./build-kitkat.sh
+ export 'AOSP_EXTRA_ARGS=-v /home/dhanasek/docker-aosp/tests/build-kitkat.sh:/usr/local/bin/run.sh:ro'
+ AOSP_EXTRA_ARGS='-v /home/dhanasek/docker-aosp/tests/build-kitkat.sh:/usr/local/bin/run.sh:ro'
+ export AOSP_IMAGE=kylemanna/aosp:4.4-kitkat
+ AOSP_IMAGE=kylemanna/aosp:4.4-kitkat
+ '[' -n '' ']'
+ '[' -x ../utils/aosp ']'
+ ../utils/aosp bash run.sh docker
+ AOSP_IMAGE=kylemanna/aosp:4.4-kitkat
+ AOSP_VOL=/home/dhanasek/docker-aosp/tests/kitkat
+ AOSP_ARGS='--rm -it'
+ AOSP_VOL_AOSP=/home/dhanasek/docker-aosp/tests/kitkat/aosp
+ AOSP_VOL_CCACHE=/home/dhanasek/docker-aosp/tests/kitkat/ccache
+ '[' '!' -d /home/dhanasek/docker-aosp/tests/kitkat/aosp -o '!' -d /home/dhanasek/docker-aosp/tests/kitkat/ccache ']'
+ '[' -n '' ']'
+ docker run --rm -it -v /home/dhanasek/docker-aosp/tests/build-kitkat.sh:/usr/local/bin/run.sh:ro -v /home/dhanasek/docker-aosp/tests/kitkat/aosp:/aosp -v /home/dhanasek/docker-aosp/tests/kitkat/ccache:/tmp/ccache kylemanna/aosp:4.4-kitkat bash run.sh docker
+ '[' docker = docker ']'
+ TEST_BRANCH=android-4.4.4_r2.0.1
+ TEST_URL=https://android.googlesource.com/platform/manifest
++ grep '^processor' /proc/cpuinfo
++ wc -l
+ cpus=4
+ repo init --depth 1 -u https://android.googlesource.com/platform/manifest -b android-4.4.4_r2.0.1
fatal: cannot make /.repoconfig directory: Permission denied
```

**Comment by kylemanna** [comment]
Hey!   The problem is file permissions.  I speculate that your local user's id and the user in the container differ.  Run `id` as your local user and see if the `uid` is different then the output of `id` from the container.

    docker run --rm -it kylemanna/aosp:4.4-kitkat id
    uid=1000(aosp) gid=1000(aosp) groups=1000(aosp)

Also, the user `docker` is what the daemon is running as the `docker` group is what controls access to the docker daemon socket.  The problem here is that `/home/dhanasek/docker-aosp/tests/kitkat` isn't writable by uid 1000 in the docker container.

To be hacky, try `chmod 777 /home/dhanasek/docker-aosp/tests/kitkat` and see if that helps.

A better solution might be more like this:

    export AOSP_VOL=$PWD/build
    mkdir $AOSP_VOL && chown 1000:1000 $AOSP_VOL
    ./build-kitkat.sh

Let me know if that works for ya!
